## Introduction

This project analyzes sea level rise over time using data from the EPA. This is important because it helps us understand the impact of climate change on the environment.

The goal of this project is to explore trends in sea level data using Python. I will use pandas to clean and analyze the data and matplotlib to visualize patterns.

This analysis can help show real evidence of climate change and support better decision-making.

## Modules Used

- pandas: used to load, clean, and analyze the dataset
- matplotlib: used to create visualizations and plots
- seaborn: used to create more advanced and visually appealing statistical graphs

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Sources

The first dataset used in this project comes from the U.S. Environmental Protection Agency (EPA):

https://www.epa.gov/climate-indicators/climate-change-indicators-sea-level

The data tracks global sea level changes over time and is used to study climate change trends. It includes variables such as year and sea level measurements.

Some values were missing (e.g., NOAA Adjusted Sea Level), and the dataset required cleaning and converting data types to numeric for analysis.

Additionally, a second dataset was used from:

https://raw.githubusercontent.com/datasets/global-temp/master/data/monthly.csv

This dataset tracks global temperature anomalies over time and is used to study climate change. The data spans from the mid-1800s to the present and includes variables such as Date and Mean temperature.

Since the data is recorded monthly, it was converted into yearly averages for analysis. This dataset will be combined with the sea level dataset using the Year variable to explore the relationship between temperature and sea level rise.

## Load Sea Level Data

This section loads the sea level dataset and prepares it for analysis.

In [4]:
url = "https://raw.githubusercontent.com/datasets/sea-level-rise/master/data/epa-sea-level.csv"
df = pd.read_csv(url)
df.head()

,Year,CSIRO Adjusted Sea Level,Lower Error Bound,Upper Error Bound,NOAA Adjusted Sea Level
0,1880,0.000000,-0.952756,0.952756,NaN
1,1881,0.220472,-0.732283,1.173228,NaN
2,1882,-0.440945,-1.346457,0.464567,NaN
3,1883,-0.232283,-1.129921,0.665354,NaN
4,1884,0.590551,-0.283465,1.464567,NaN

## Clean Sea Level Data

This section cleans the dataset by renaming columns and converting values to numeric for analysis.

In [5]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      144 non-null    int64
 1   CSIRO Adjusted Sea Level  134 non-null    float64
 2   Lower Error Bound         134 non-null    float64
 3   Upper Error Bound         134 non-null    float64
 4   NOAA Adjusted Sea Level   31 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 5.8 KB

,Year,CSIRO Adjusted Sea Level,Lower Error Bound,Upper Error Bound,NOAA Adjusted Sea Level
count,144.000000,134.000000,134.000000,134.000000,31.000000
mean,1951.500000,3.646404,3.201551,4.091256,8.120275
std,41.713307,2.477596,2.657303,2.302755,1.125552
min,1880.000000,-0.440945,-1.346457,0.464567,6.308803
25%,1915.750000,1.632874,1.078740,2.240157,7.197893
50%,1951.500000,3.312992,2.915354,3.710630,7.960706
75%,1987.250000,5.587598,5.329724,5.845472,9.127353
max,2023.000000,9.244094,8.917323,9.570866,10.203904

## Load Temperature Data

This section loads the global temperature dataset for analysis.

In [6]:
temp = pd.read_csv("https://raw.githubusercontent.com/datasets/global-temp/master/data/monthly.csv")
temp.head()

  Source     Year    Mean
0   gcag  1850-01 -0.6746
1   gcag  1850-02 -0.3334
2   gcag  1850-03 -0.5913
3   gcag  1850-04 -0.5887
4   gcag  1850-05 -0.5088

## Clean Temperature Data

This section prepares the temperature dataset by extracting the year and calculating yearly average temperature values.

In [7]:
temp["Year"] = temp["Year"].astype(str).str[:4]
temp["Year"] = pd.to_numeric(temp["Year"], errors="coerce")

temp_yearly = temp.groupby("Year")["Mean"].mean().reset_index()

temp_yearly.head()

   Year      Mean
0  1850 -0.417708
1  1851 -0.233342
2  1852 -0.229400
3  1853 -0.270350
4  1854 -0.291517

In [8]:
merged = pd.merge(df, temp_yearly, on="Year", how="inner")
merged.head()

,Year,CSIRO Adjusted Sea Level,Lower Error Bound,Upper Error Bound,NOAA Adjusted Sea Level,Mean
0,1880,0.000000,-0.952756,0.952756,NaN,-0.244167
1,1881,0.220472,-0.732283,1.173228,NaN,-0.160287
2,1882,-0.440945,-1.346457,0.464567,NaN,-0.201096
3,1883,-0.232283,-1.129921,0.665354,NaN,-0.260325
4,1884,0.590551,-0.283465,1.464567,NaN,-0.386579

In [9]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      144 non-null    int64
 1   CSIRO Adjusted Sea Level  134 non-null    float64
 2   Lower Error Bound         134 non-null    float64
 3   Upper Error Bound         134 non-null    float64
 4   NOAA Adjusted Sea Level   31 non-null     float64
 5   Mean                      144 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 6.9 KB

In [10]:
merged.describe()

,Year,CSIRO Adjusted Sea Level,Lower Error Bound,Upper Error Bound,NOAA Adjusted Sea Level,Mean
count,144.000000,134.000000,134.000000,134.000000,31.000000,144.000000
mean,1951.500000,3.646404,3.201551,4.091256,8.120275,0.024146
std,41.713307,2.477596,2.657303,2.302755,1.125552,0.385555
min,1880.000000,-0.440945,-1.346457,0.464567,6.308803,-0.537512
25%,1915.750000,1.632874,1.078740,2.240157,7.197893,-0.254462
50%,1951.500000,3.312992,2.915354,3.710630,7.960706,-0.070542
75%,1987.250000,5.587598,5.329724,5.845472,9.127353,0.236400
max,2023.000000,9.244094,8.917323,9.570866,10.203904,1.134742

In [11]:
merged.shape

(144, 6)